### ISSUE TITLE
Top !

### ISSUE THREAD

**Issue by thsfo** [YunoHost-Apps/prettynoemiecms_ynh#8]
Cool super !
Des remarques..

- Un ch'tit module _embarquement_ pourrait pallier à des modules qui pourraient manquer.
- Ce serait top de pouvoir embarquer des trucs sociaux genre video de peertube, évènements de mobilizon

Merci bien c'est génial en tout cas.

**Comment by kay0u** [comment]
Bonjour, et merci pour le retour!

N'étant qu'un package de l'app prettynoemiecms, je pense qu'il serait cependant plus approprié de faire ces suggestions sur le [dépôt du développeur](https://framagit.org/framasoft/PrettyNoemieCMS).
