### ISSUE TITLE
Two installations on the same internet cube …

### ISSUE THREAD

**Issue by ghost** [YunoHost-Apps/prettynoemiecms_ynh#9]
Under 2 YunoHost 3.6.5.3 (stable) installer on a lime1 and a lime2, we are two to have the same error when we install two PrettyNoemie.

For instance on my lime1
- https://tierce.nohost.me/prettynoemiecms/
- https://tierce.nohost.me/machin

The second installation _(under /machin)_ gives me an error

    HTTP 404 (GET /machin/signIn)

    [vendor/bcosca/fatfree/lib/base.php:1675] Base->error()
    [index.php:28] Base->run()

 and I know another person having the same issue.

Any idea ?

**Comment by ceclic-h1** [comment]
Hello

idem slim2
https://ceclic.nohost.me/cv
https://ceclic.nohost.me/g1group

I speak not english.

Thanks

**Comment by kay0u** [comment]
Hi, and thank you for your issue.

Should be fixed by #13
